name: CI

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone E2E Repository
        uses: actions/checkout@v4
        with:
          repository: LeoCpii/fake-cypress
          path: e2e-tests

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install dependencies for E2E
        run: yarn install --immutable
        working-directory: ./e2e-tests

      - name: Build
        run: |
          yarn build

      - name: Start Portal Application
        run: |
          yarn start &
          sleep 15
        working-directory: ./
      
      - name: Run E2E Tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./e2e-tests
          wait-on: 'http://localhost:3000'  # URL onde o Portal estará disponível
          command: yarn test
  